import time

from .configs import (
    WORKDIR, 
    MODEL, 
    SUBAGENT_MODEL, 
    HARNESS_DIR,
    SKILL_DIR,
    CONTEXT_LIMIT,
    PERSIST_TOOL_RESULT,
    PERSIST_THRESHOLD,
    PREVIEW_CHARS,
    TOOL_RESULTS_DIR,
    KEEP_RECENT_TOOL_RESULTS,
    TRANSCRIPT_DIR,
    DEFAULT_RULES,
    MEMORY_DIR,
    MEMORY_INDEX,
    MEMORY_TYPES,
    MAX_INDEX_LINES,
    DYNAMIC_BOUNDARY,
    MAX_RECOVERY_ATTEMPTS,
    TOKEN_THRESHOLD
)

now = time.time()
